name: muzik
favicon: null
layout_spectrum: 0.48827
typography_spectrum: 0.1900910458061844
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a3a7b0'
    - '#fbf8f3'
    - '#4d5055'
    - '#818689'
    - '#1e1d19'
  brandStrength: 0.33495762827806175
  lightness: 0.12289231736212969
  saturation: 0.6010305385570973
  rhythmicContrast: 0.5766159538179636
purpose: []
