name: muzik
favicon: null
layout_spectrum: 0.7827608622610569
typography_spectrum: 0.1900910458061844
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.33495762827806175
  lightness: 0.12289231736212969
  saturation: 0.6010305385570973
  rhythmicContrast: 0.5766159538179636
purpose: []
