name: muzik
favicon: null
layout_spectrum: 0
typography_spectrum: 0.1900910458061844
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fc408d'
    - '#fbdf40'
    - '#0a0501'
    - '#5d0d02'
    - '#ae9a37'
  brandStrength: 0.33495762827806175
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.5766159538179636
purpose: []
