name: muzik
favicon: null
layout_spectrum: 0.50836
typography_spectrum: 0.1900910458061844
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fc408d'
    - '#fbdf40'
    - '#0a0501'
    - '#5d0d02'
    - '#ae9a37'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
