favicon: null
name: muzik
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.375
  brandStrength: 0.1875
  rhythmicContrast: 0.75
  brandColors:
    - '#fc408d'
    - '#fbdf40'
    - '#0a0501'
    - '#5d0d02'
    - '#ae9a37'
  lightness: 0.3125
typography_spectrum: 0.3172043
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.50836
analytics:
  twitter: null
  google: null
  facebook: null
