favicon: null
name: muzik
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.41269374056719244
  brandStrength: 0.6552508750464767
  rhythmicContrast: 0.8382968278601766
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  lightness: 0.18849009601399302
typography_spectrum: 0.5766352647915483
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.08312967559322715
analytics:
  twitter: null
  google: null
  facebook: null
